### ISSUE TITLE
Use relative imports

### ISSUE THREAD

**Issue by dastultz** [peterhinch/Micropython-scheduler#1]
Hi Peter, this is working well for me, thanks!

I've cloned the project, then used symlinks to get it in to my project, so `my_project/lib/scheduler` links to your `lib` directory. To make this work I had to change the imports to be relative. So `from usched import Sched, Timeout` was changed to `from .usched import Sched, Timeout` for example.

If you think it's a good idea, maybe you could add that change (to all imports within the project), unless there's a better "Pythonic/Pyboard" way to do this. I just `rsync` my project directory to the pyboard.

Thanks!

**Comment by peterhinch** [comment]
I'll consider that one. The scheduler was my first Pyboard project (I have a habit of writing a scheduler for any new platform I take to). I made the mistake of putting most of the documentation into the code. This was born of habit using compilers, but obviously on the Pyboard it wastes Flash space. I've been planning to update the project to fix this, but it may be a while before I find time.

**Comment by peterhinch** [comment]
On reflection I'm not keen on relative imports and they don't seem to be used elsewhere in the MicroPython project. An alternative approach is to modify ``sys.path`` in ``boot.py`` or elsewhere. So unless you or others come up with a compelling reason to change the code I intend to pass on this one.

**Comment by dastultz** [comment]
Ok, so I've read that relative imports are frowned upon. I make my living writing Java where libraries are incorporated by placing a jar file in a lib folder which is typically included on the class path as Micropython includes lib on the sys path (at least with the pyboard). Naming conflicts are avoided by prepending a directory structure that is the inverse of a web site domain such as org/micropython. When I look at site-packages on my machine I see mostly directories such as numpy. Inside that I see a file dual.py with an import like "import numpy.fft". In this project the py files are all at the "top level" of lib. If someone else makes a library with "switch.py", well they can't coexist and it puts the onus on the user to manage such conflicts. In lieu of relative imports would you consider placing the py files under lib/usched/ instead? So the compelling reason is "drop-in compatibility with other libraries".

Thanks!
