### ISSUE TITLE
Help TypeError: 'int' object is not an iterator

### ISSUE THREAD

**Issue by dothacker495** [peterhinch/Micropython-scheduler#3]
I tried usched.py and roundrobin.py in my esp8266 Micropython port. I seem to get an error using Sched().run function:

> **Traceback (most recent call last):
>   File "<stdin>", line 32, in <module>
>   File "<stdin>", line 30, in test
>   File "usched.py", line 297 in run
>   File "usched.py", line 1, in <listcomp>
> TypeError: 'int' object is not an iterator**

  I don't really understand why, I inserted **print(objSched.lstThread)** above _line 30:  objSched.run()_ 
and it printed:

> [[None, <generator object 'robin' at 3fff2c50>, 1, 1, True], [None, <generator object 'robin' at 3fff2cf0>, 2, 1, True], [None, <generator object 'robin' at 3fff2d40>, 3, 1, True], [5, <generator object 'stop' at 3fff2e00>, 4, 1, True]]

Any idea?

roundrobin.py
```
# roundrobin.py Runs three threads in round robin fashion. Stops after a duration via a timeout thread.
# Author: Peter Hinch
# Copyright Peter Hinch 2016 Released under the MIT license

import time
from usched import Sched

# Run on MicroPython board bare hardware
# THREADS:

def stop(fTim, objSch):                                     # Stop the scheduler after fTim seconds
    yield fTim
    print('Stopping')
    objSch.stop()

def robin(text):
    while True:
        print(text)
        yield

# USER TEST PROGRAM

def test(duration = 0):
    objSched = Sched(True, 1) # heartbeat on LED 1
    objSched.add_thread(robin("Thread 1"))
    objSched.add_thread(robin("Thread 2"))
    objSched.add_thread(robin("Thread 3"))
    if duration:
        objSched.add_thread(stop(duration, objSched))       # Kill after a period
    print(objSched.lstThread)
    objSched.run()

test(5)

```

**Comment by peterhinch** [comment]
You haven't mentioned if you are using frozen bytecode. If not I think you may be encountering memory allocation issues. The ESP8266 has limited RAM and all my testing of the scheduler has been with usched.py implemented as frozen bytecode. Running in that way your code works here on the reference board.

I then flashed an ESP board with a firmware build lacking usched.py and copied that file to the filesystem. I copied and pasted your code from ``import time`` to just before ``USER TEST PROGRAM`` and got a memory allocation failure on line 2. I think the compiler is failing to compile usched.py - verified by hitting ``<ctrl>D`` and then

```python
import usched
```

which gave a memory error.

If you are implementing the scheduler as frozen bytecode let me know and I'll try to investigate further. Your display of the threadlist looks correct, by the way, which puzzles me as I can't even import the module.

Incidentally, as you've discovered, I haven't yet updated the test programs to work on the ESP.

**Comment by dothacker495** [comment]
I placed usched.py in `<DIR>/micropython/esp8266/modules` and I didn't encounter any problem after building the firmware and using the other parts of usched.py.

Yup, there were some parts i modified to cater ESP like in Pinblock class, but nonetheless I'm currently hanged up by the error

> **TypeError: 'int' object is not an iterator**

I don't understand why micropython treated self.lstThread as an 'int' object  in this line
`  self.lstThread = [thread for thread in **self.lstThread** if thread[STATE] != DEAD] # Remove dead threads`

**Comment by dothacker495** [comment]
Okay my simple workaround solved the problem. I don't know why the single liner didn't work for me
```
 class Poller(Waitfor):
     def __init__(self, pollfunc, pollfunc_args = (), timeout = None):
@@ -193,7 +190,10 @@ class Sched(object):
                 self.heartbeat = machine.Pin(2, machine.Pin.OUT)
 
     def __getitem__(self, pid):                 # Index by pid
-        threads = [thread for thread in self.lstThread if thread[PID] == pid]
+        threads = []
+        for thread in self.lstThread:
+          if(thread[PID] == pid):
+            threads.append(thread)
         if len(threads) == 1:
             return threads[0]
         elif len(threads) == 0:
@@ -270,7 +270,10 @@ class Sched(object):
     def _get_thread(self):
         p_run = None                        # priority tuple of thread to run
         thr_run = None                      # thread to run
-        candidates = [t for t in self.lstThread if t[STATE] == RUNNING]
+        candidates = []
+        for t in self.lstThread:
+          if(t[STATE] == RUNNING):
+            candidates.append(t)
         for thread in candidates:
             priority = self.triggered(thread)
             if priority is not None:        # Ignore threads waiting on time or event
@@ -294,7 +297,12 @@ class Sched(object):
 
     def run(self):                              # Returns if the stop method is used or all threads terminate
         while not self.bStop:
-            self.lstThread = [thread for thread in self.lstThread if thread[STATE] != DEAD] # Remove dead threads
+            tempThread = []
+            for thread in self.lstThread:
+              if(thread[STATE] is not DEAD):
+                tempThread.append(thread) # Remove dead threads
+            self.lstThread = tempThread
+            gc.collect()

```

**Comment by peterhinch** [comment]
I'm loath to change usched.py without understanding the problem! I'm baffled by the symptoms you're seeing and can't replicate them here. On the face of it the behaviour you're seeing is obscure: you're printing out a properly formed threadlist, then issuing run() and immediately it's behaving as if the list were an int. It would be good if we could find the root cause. Perhaps get run() to print the list before doing the list comprehension?

I'm at a a loss as to what I can do here until I can replicate the fault. For what it's worth I've been using it on the ESP8266 in an application which makes extensive use of round robin scheduling and have encountered no problems.

**Comment by dothacker495** [comment]
I'm also confused why the list is treated as an 'int' object. I did print the lstThread before it reaches the list comprehension/s, the result was a valid list object though. Yup my firmware build is up to date ( last update was Sept 30,2016). Anyway at least when someone experiences what i experienced they could just read this. Sorry for taking up your time

**Comment by peterhinch** [comment]
No problem, I'd very much like to know the cause, which looks to me more like a MicroPython/ESP8266 issue than one specific to the scheduler. I assume you've tried simple tests of list comprehensions at the REPL? For what it's worth I've never experienced issues with list comprehensions in over two years MicroPython programming. However the ESP8266 is very RAM constrained and still not an entirely stable platform. Evidently *something* is going wrong.

**Comment by dothacker495** [comment]
Yes i think so too. Yes I have tried list comprehensions in some of my code in micropython which is really weird. Anyway thanks to your scheduler, coding is a bit easier

**Comment by peterhinch** [comment]
Micropython issue #2446 may have the answer. Have you recompiled the cross compiler?

**Comment by dothacker495** [comment]
I tried updating then recompiling everything from esp open sdk to micropython esp8266. I still get this error

```

>   File "usched.py", line 303, in run
>   File "usched.py", line 1, in <listcomp>
> TypeError: 'int' object is not an iterator
> 

```

I'll try raising this issue in Micropython esp8266 github
