### ISSUE TITLE
Issue on ESP8266

### ISSUE THREAD

**Issue by iosix** [peterhinch/Micropython-scheduler#4]
I'm seeing this error on micropython 1.8.4 running on ESP8266 dev board:

>>> micropython.mem_info()
stack: 1952 out of 8192
GC: total: 28160, used: 7472, free: 20688
 No. of 1-blocks: 49, 2-blocks: 12, max blk sz: 263, max free sz: 1088
>>> import usched
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
MemoryError:
>>> micropython.mem_info()
stack: 1952 out of 8192
GC: total: 28160, used: 12944, free: 15216
 No. of 1-blocks: 84, 2-blocks: 37, max blk sz: 263, max free sz: 177
>>>

Any thoughts?  Thanks!

**Comment by dothacker495** [comment]
Did you try implementing usched.py as frozen bytecode? 
I always do ^this to avoid memory error

**Comment by iosix** [comment]
Hmm, I tried compiling it into a pyc and loading that, but micropython doesn't think the module is valid ("ImportError: no module named usched").  Are you suggesting I should recompile micropython instead?  Thanks.

**Comment by peterhinch** [comment]
The only way to run the scheduler on ESP8266 is as frozen bytecode. The ESP does not (yet?) support loading cross compiled bytecode files.

This involves putting usched.py in esp8266/modules, recompiling, and flashing the firmware. Rather than build the toolchain I use a nightly build from [here](http://www.kaltpost.de/~wendlers/micropython/).

**Comment by iosix** [comment]
Sweet.  I was able to get it to work with that method.  Possibly I missed it in the readme/front git page?  If not I would suggest adding it.  Very cool work by the way!

**Comment by peterhinch** [comment]
I've updated the README to clarify the need for frozen bytecode on the ESP8266. Thanks for the pointer.
